/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tpn2amado;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.BufferedReader; 
import java.io.File; 
import java.io.FileReader; 
import java.io.FileWriter; 
import javax.swing.JOptionPane;
/**
 *
 * @author amado
 */
public class Window extends javax.swing.JFrame {
    ArrayList<TSocio> asociados;//declaro array List de tipo TSocio
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        asociados = InicioLista.iniciarArchivo();//invoco método que me trae arrayList armada para iniciar con todo cargado
        txaSalida.setText(InicioLista.salidaTexto());//invoco método que retorna la arratList pasada a String
        /*
            esté bloque asegura volver a establecer el num de socios donde se quedo cuando se cerro
        */
        if (!asociados.isEmpty()) {//si asociado no esta vacío
            TSocio ultimoSocio = asociados.get(asociados.size() - 1);//consigo el último Tsocio de la lista (tamaño -1 para obtener la posición)
            int contadorSocio = ultimoSocio.getNumeroSocio();//de ese TSocio obtengo el número y lo guardo en un int
            TSocio.setContadorSocio(contadorSocio);//re-establezco el contador de socios
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etiNombre = new javax.swing.JLabel();
        etiApellido = new javax.swing.JLabel();
        etiDNI = new javax.swing.JLabel();
        etiTel = new javax.swing.JLabel();
        etiCat = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        cbCategoria = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaSalida = new javax.swing.JTextPane();
        btnAbrir = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtBorrarSocio = new javax.swing.JTextField();
        txtFichero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("U.N.L. F.I.C.H. Elementos de Programación TPNº2");

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setText("Gestor de Socios");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Socio:");

        etiNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        etiNombre.setText("Nombre: ");

        etiApellido.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        etiApellido.setText("Apellido:");

        etiDNI.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        etiDNI.setText("DNI:");

        etiTel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        etiTel.setText("Teléfono: ");

        etiCat.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        etiCat.setText("Categoría:  ");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menor", "Cadete", "Mayor" }));
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Menor de 0 a 12 años, Cadete de 13 a 18 años, Mayor con mas de 18 años");

        btnAgregar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jScrollPane1.setViewportView(txaSalida);

        btnAbrir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Borrar Socio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        btnEliminar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Número de Socio: ");

        txtBorrarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBorrarSocioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBorrarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194)
                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtBorrarSocio))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        txtFichero.setText("socios.txt");
        txtFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFicheroActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Fichero:");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ficheros en carpeta del programa");

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFichero, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                            .addComponent(btnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addGap(3, 3, 3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(5, 5, 5)))
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        btnGuardar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addGap(166, 166, 166))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(etiTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(etiCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(etiDNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(etiApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(etiNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(6, 6, 6)))
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre)
                                            .addComponent(txtDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                            .addComponent(txtTel, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                            .addComponent(cbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                        .addGap(147, 147, 147)))
                                .addGap(183, 183, 183))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(etiNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(etiApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDNI)
                            .addComponent(etiDNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTel)
                                .addGap(7, 7, 7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(etiTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(etiCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        /**
         * botón que agrega socios
         * parámetros del constructor
         * los obtiene de lo que relleno el usuario en la interfaz
         */
        int telefono, dni;
        String nombre, apellido, categoria;
        nombre = txtNombre.getText();
        apellido = txtApellido.getText();
        dni = Integer.parseInt(txtDNI.getText());
        telefono = Integer.parseInt(txtTel.getText());
        categoria = (String) cbCategoria.getSelectedItem();//usé comboBox para que solo tomé los string válidos
        
        TSocio socioNuevo = new TSocio(nombre, apellido, dni, telefono, categoria);//constructor creando un TSocio
        asociados.add(socioNuevo);//agrega el TSoocio al arrayList
        
        txaSalida.setText(socioNuevo.toString());//muestra por pantalla al socioNuevo
         
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        /**
         * Botón para borrar un socio con el nª de socio
         */
        int socioOut = Integer.parseInt(txtBorrarSocio.getText());//conseguir el num de socio
        Iterator<TSocio> iterator = asociados.iterator();        // Crear un iterador para la lista
        while (iterator.hasNext()) {//recorre la arrayLista
            TSocio socioX = iterator.next();  // Obtener el siguiente elemento
            int num = socioX.getNumeroSocio();//consigue el numero del socio de la vuelta actual
            if (num == socioOut) {//compara los números
                // Eliminar el elemento actual 
                iterator.remove();//borra el socio (me resulta algo confusa la sintaxís)
            }
        }
        
        StringBuilder salida = new StringBuilder();
        
        for (TSocio socio : asociados) {
            salida.append(socio.toString()).append("\n");//En salida guardo cada TSocio pasado a String
        }
        txaSalida.setText(salida.toString());//imprimo salida
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBorrarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBorrarSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBorrarSocioActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        /*
        Armar una lista con los agregados + la lista del arrayList
        mostrando cada TSocio
        */
        StringBuilder salida = new StringBuilder();//El String que no llena la memoría
        
        //Por cada TSocio en la lista va a iterar lo va a pasar a texto
        //Y lo agrega al StringBuilder
        for (TSocio socio : asociados) {
            salida.append(socio.toString()).append("\n");
        }
        txaSalida.setText(salida.toString());//reutilizo mucho esto quisiera pasarlo a una function si da el tiempo (pero no se si es adecuado en JAVA ya que deberia ser un metodo y no se de quien)
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        /**
         * Guarda el archivo 
         */
        try {
        File archivo = new File(txtFichero.getText());//toma el nombre de la caja de texto
//podemos modificar para tomar el Path, pero por seguridad creo mejor dejar todo en la carpeta
        boolean nuevoArchivo = false;//bandera
        
        // Verificar si el archivo ya existe
        if (archivo.exists()) {
            //pregunta con ventana emergente
            int opcion = JOptionPane.showConfirmDialog(null, "El archivo ya existe. ¿Desea sobrescribirlo?, si elige no sobrescribir, se guardará con otro nombre", "Confirmación", JOptionPane.YES_NO_OPTION);
            
            //verifica si existe y si se quiere sobrescribir o generar uno nuevo
            if (opcion == JOptionPane.YES_OPTION) {
                nuevoArchivo = false; // Sobrescribir el archivo
            } else if (opcion == JOptionPane.NO_OPTION) {
            // Genera un número aleatorio 
                nuevoArchivo = true; // Crear un nuevo archivo
            }
        } else {
            nuevoArchivo = false; // Crear archivo ya que no existe
        }
        
        
        String nuevo = "socios_nuevo" + String.valueOf(TSocio.getContadorSocio() + ".txt");//para seguridAD de no sobrescribir hay que tomar alguna medida más
        // Escribir en el archivo correspondiente
        String archivoNombre = nuevoArchivo ? nuevo : "socios.txt";//ternario para ver el nombre
        File archivoGuardar = new File(archivoNombre);
        
        //el param viene de las líneas de arriba dondé se ve se guarda el texto en la variable dependiendo del ternario
        try (FileWriter escribir = new FileWriter(archivoGuardar)) {
            for (TSocio socio : asociados) {
                escribir.write(socio.toString() + "\n");
            }
            escribir.flush();//actualiza
        }
    } catch (Exception e) {
        txaSalida.setText("Error en la creación del archivo: " + e.getMessage());
    }
        
        
    StringBuilder salida = new StringBuilder();//reutilizo el código de listar para actualizar la vista
    for (TSocio socio : asociados) {
        salida.append(socio.toString()).append("\n");
    }
    txaSalida.setText(salida.toString());
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
    /**
     * El botón de abrir revisa el nombre del fichero ingresado e intenta abrirlo
     * lo recorre y va tomando los datos por concurrencia para armar nuevamente la arrayList
     * luego nos muestra una versión pasada a string por txaSalida
     */
    String ficheroSocios = txtFichero.getText();
    // Lectura del archivo 
    int dni, telefono, numeroSocio;
    String apellido, nombre, categoria;//modificar a String buffer/builder
    nombre = null;
    apellido = null;
    categoria = null;
    dni = 0;
    telefono = 0;
    numeroSocio = 0;
    TSocio socioActual = null;

    // ArrayList para almacenar los socios
    if (asociados != null) {//agregue esto por si ya se habían tocado otras opciones antes
        asociados.clear();//lo limpia
        txaSalida.setText(" ");//limpia la salida de texto
    } else {
        asociados = new ArrayList<>(); // Si listaSocios es null, la inicializamos
    }
    //nota de problema e intento para mí, se estaba generando un socio con los datos que tuve que usar para inicializar las variables. Los moví de scoupe
   
    
    /*
    abre archivo
    lo lee por líneas
    busca datos por concurrencia y llena variables para parámetros del constructor
    crea los TSocio y los agrega al arrayList
    */
    try {
        FileReader lector = new FileReader(ficheroSocios);//recorro linea por linea el fichero
        BufferedReader contenido = new BufferedReader(lector);    
        String linea;
        // Recorremos el archivo línea por línea
        while ((linea = contenido.readLine()) != null) {
            //recorremos las lineas actualizando variables
            if (linea.startsWith("Nombre:")) {//busco concurrencias para tomar datos y modificar variables
                nombre = linea.substring("Nombre: ".length());
            } else if (linea.startsWith("Apellido:")) {
                apellido = linea.substring("Apellido: ".length());
            } else if (linea.startsWith("DNI:")) {
                dni = Integer.parseInt(linea.substring("DNI: ".length()));
            } else if (linea.startsWith("Teléfono:")) {
                telefono = Integer.parseInt(linea.substring("Teléfono: ".length()));
            } else if (linea.startsWith("Categoría: ")) {
                categoria = linea.substring("Categoría: ".length());
            } else if (linea.startsWith("Socio Nº")) {
                numeroSocio = Integer.parseInt(linea.substring("Socio Nº".length()));
            }
            
            if (linea.startsWith("Teléfono:")) {//uso ese texto PARA SABER SI ya toca crear uno objeto
                socioActual = new TSocio(nombre, apellido, dni, telefono, categoria, numeroSocio);
                asociados.add(socioActual);
                nombre = null;//reinicio variables por seguridad
                apellido = null;
                categoria = null;
                dni = 0;
                telefono = 0;
                numeroSocio = 0;
                socioActual = null;
            }
        }
    lector.close();//cerramos el lectorr    
    }
    catch (Exception e) {
         txaSalida.setText("ERROR: No se pudo leer el archivo");
    }
    
    //armamos el String con el arrayList
    StringBuilder salida = new StringBuilder();
    for (TSocio socio : asociados) {
        salida.append(socio.toString()).append("\n");
    }
    txaSalida.setText(salida.toString());//Imprimimos 
    
    //configuramos contadorSocio de la clase TSocio
    if (!asociados.isEmpty()) {//si no está vacío conseguimos el número de socios
        TSocio ultimoSocio = asociados.get(asociados.size() - 1);
        int contadoSocioLista = ultimoSocio.getNumeroSocio();
        TSocio.setContadorSocio(contadoSocioLista);
    }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void txtFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFicheroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFicheroActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        //reutilizo el código de guardar con modificaciones
        /**
         * Botón que cierra pero antes te permite guardar
         */
        int opcionCerrar = JOptionPane.showConfirmDialog(null, "Desea Guardar", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (opcionCerrar == JOptionPane.YES_OPTION){
            try {
            File archivo = new File(txtFichero.getText());//podemos modificar para tomar el Path, pero por segurirdad creo mejor dejar todo en la carpeta
            boolean nuevoArchivo = false;
        
            // Verificar si el archivo ya existe
            if (archivo.exists()) {
                int opcion = JOptionPane.showConfirmDialog(null, "El archivo ya existe. ¿Desea sobrescribirlo?, si elige no sobrescribir, se guardará con otro nombre", "Confirmación", JOptionPane.YES_NO_OPTION);
            
                if (opcion == JOptionPane.YES_OPTION) {
                    nuevoArchivo = false; // Sobrescribir el archivo
                } else if (opcion == JOptionPane.NO_OPTION) {
                // Genera un número aleatorio 
                    nuevoArchivo = true; // Crear un nuevo archivo
                }
            } else {
                nuevoArchivo = false; // Crear archivo ya que no existe
            }
            String nuevo = "socios_nuevo" + String.valueOf(TSocio.getContadorSocio() + ".txt");//para seguridAD de no sobreescribir hay que tomar alguna medida más
            // Escribir en el archivo correspondiente
            String archivoNombre = nuevoArchivo ? nuevo : "socios.txt";//ternario para ver el nombre
            File archivoGuardar = new File(archivoNombre);
        
            try (FileWriter escribir = new FileWriter(archivoGuardar)) {
                for (TSocio socio : asociados) {
                    escribir.write(socio.toString() + "\n");
                }
                escribir.flush();
            }
            System.exit(0);
        } catch (Exception e) {
            txaSalida.setText("Error en la creación del archivo: " + e.getMessage());
        }////////////////////////////////////////////////Si hay error no debería cerrar
        } else {
            System.exit(0);//cerrar código
        }
        
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JLabel etiApellido;
    private javax.swing.JLabel etiCat;
    private javax.swing.JLabel etiDNI;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JLabel etiTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txaSalida;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBorrarSocio;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtFichero;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
